<?xml version="1.0"?>
<package format="3">
  <name>lio_sam_sim_adapter</name>
  <version>0.0.1</version>

  <description>
    ROS 2 adapter for converting simulated LiDAR point clouds for LIO-SAM.
  </description>

  <maintainer email="yez@example.com">yez</maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
